/** Data-driven catalog. Seed is idempotent upserts from this file. */

export const waterbodies = [
  {
    id: "forest-lake",
    slug: "forest-lake",
    name: "Лесное озеро",
    kind: "forest_lake",
    description:
      "Тихая вода среди сосен. Камыш, старый мостик, коряжник и яма у северного берега.",
    region: "forest",
    minLevel: 1,
    exploration: { spots: 5, secrets: 1 },
    visual: { palette: "dawn-pine", parallax: true },
    seasonality: { ice: false },
  },
];

export const spots = [
  {
    id: "old-bridge",
    waterbodyId: "forest-lake",
    slug: "old-bridge",
    name: "Старый мостик",
    kind: "bridge",
    description: "Обветшалые доски над сваей. Удобно для поплавка.",
    depthMinM: 0.8,
    depthMaxM: 2.2,
    current: 0.05,
    vegetation: 0.35,
    trophyChance: 0.07,
    secret: false,
    methods: ["FLOAT", "BOTTOM"] as const,
  },
  {
    id: "reed-bank",
    waterbodyId: "forest-lake",
    slug: "reed-bank",
    name: "Камышовый берег",
    kind: "reeds",
    description: "Узкие окна в камыше. Осторожная рыба и краснопёрка.",
    depthMinM: 0.4,
    depthMaxM: 1.6,
    current: 0,
    vegetation: 0.85,
    trophyChance: 0.06,
    secret: false,
    methods: ["FLOAT", "SPINNING"] as const,
  },
  {
    id: "deep-hole",
    waterbodyId: "forest-lake",
    slug: "deep-hole",
    name: "Глубокая яма",
    kind: "hole",
    description: "Резкий свал. Лещ, судак, крупный окунь.",
    depthMinM: 2.8,
    depthMaxM: 5.5,
    current: 0.1,
    vegetation: 0.15,
    trophyChance: 0.14,
    secret: false,
    methods: ["FLOAT", "FEEDER", "BOTTOM", "SPINNING"] as const,
  },
  {
    id: "snag",
    waterbodyId: "forest-lake",
    slug: "snag",
    name: "Коряжник",
    kind: "snags",
    description: "Затопленные стволы. Щука и риск обрыва.",
    depthMinM: 1.4,
    depthMaxM: 3.4,
    current: 0.08,
    vegetation: 0.55,
    trophyChance: 0.16,
    secret: false,
    methods: ["SPINNING", "FLOAT"] as const,
  },
  {
    id: "sandy-spit",
    waterbodyId: "forest-lake",
    slug: "sandy-spit",
    name: "Песчаная коса",
    kind: "sand",
    description: "Отмель, которую видно только с лодки или после разведки.",
    depthMinM: 0.6,
    depthMaxM: 1.8,
    current: 0.02,
    vegetation: 0.2,
    trophyChance: 0.09,
    secret: true,
    methods: ["FLOAT", "SPINNING"] as const,
  },
];

type SpeciesSeed = {
  id: string;
  slug: string;
  name: string;
  description: string;
  minWeightG: number;
  avgWeightG: number;
  maxWeightG: number;
  minLengthCm: number;
  maxLengthCm: number;
  rarity: "COMMON" | "UNCOMMON" | "RARE" | "EPIC" | "LEGENDARY";
  trophyWeightG: number;
  recordWeightG: number;
  baseXp: number;
  baseValue: number;
  fightProfile: { pull: number; directionChange: number; coverSeek: number; stamina: number };
  activity: {
    seasons: Array<"SPRING" | "SUMMER" | "AUTUMN" | "WINTER">;
    times: Array<"DAWN" | "MORNING" | "DAY" | "EVENING" | "DUSK" | "NIGHT">;
    weather: Array<"CLEAR" | "PARTLY_CLOUDY" | "OVERCAST" | "RAIN" | "DOWNPOUR" | "STORM" | "FOG" | "WIND" | "CALM" | "SNOW">;
    depthMinM: number;
    depthMaxM: number;
    tempMinC: number;
    tempMaxC: number;
  };
  baits: string[];
  lures: string[];
  behavior: string;
  legendary?: boolean;
  legendaryLore?: string;
  spots: Array<{ spotId: string; weight: number }>;
};

export const species: SpeciesSeed[] = [
  {
    id: "crucian",
    slug: "crucian",
    name: "Карась",
    description: "Осторожный житель тихой воды. Слабое сопротивление, любит червя и хлеб.",
    minWeightG: 80,
    avgWeightG: 280,
    maxWeightG: 1800,
    minLengthCm: 12,
    maxLengthCm: 38,
    rarity: "COMMON",
    trophyWeightG: 800,
    recordWeightG: 1300,
    baseXp: 14,
    baseValue: 8,
    fightProfile: { pull: 0.25, directionChange: 0.2, coverSeek: 0.15, stamina: 0.5 },
    activity: {
      seasons: ["SPRING", "SUMMER", "AUTUMN"],
      times: ["DAWN", "MORNING", "EVENING", "DUSK"],
      weather: ["CLEAR", "PARTLY_CLOUDY", "OVERCAST", "CALM", "FOG"],
      depthMinM: 0.5,
      depthMaxM: 2.2,
      tempMinC: 12,
      tempMaxC: 26,
    },
    baits: ["worm", "bread", "corn", "dough"],
    lures: [],
    behavior: "cautious",
    spots: [
      { spotId: "old-bridge", weight: 1.4 },
      { spotId: "reed-bank", weight: 1.6 },
      { spotId: "sandy-spit", weight: 1.1 },
    ],
  },
  {
    id: "roach",
    slug: "roach",
    name: "Плотва",
    description: "Стайная серебристая рыба. Держится у камыша и мостика.",
    minWeightG: 40,
    avgWeightG: 160,
    maxWeightG: 700,
    minLengthCm: 10,
    maxLengthCm: 32,
    rarity: "COMMON",
    trophyWeightG: 350,
    recordWeightG: 520,
    baseXp: 10,
    baseValue: 5,
    fightProfile: { pull: 0.3, directionChange: 0.35, coverSeek: 0.1, stamina: 0.4 },
    activity: {
      seasons: ["SPRING", "SUMMER", "AUTUMN"],
      times: ["MORNING", "DAY", "EVENING"],
      weather: ["CLEAR", "PARTLY_CLOUDY", "OVERCAST", "RAIN", "CALM"],
      depthMinM: 0.4,
      depthMaxM: 2.5,
      tempMinC: 8,
      tempMaxC: 24,
    },
    baits: ["maggot", "bloodworm", "bread", "worm"],
    lures: [],
    behavior: "schooling",
    spots: [
      { spotId: "old-bridge", weight: 1.2 },
      { spotId: "reed-bank", weight: 1.5 },
      { spotId: "sandy-spit", weight: 1 },
    ],
  },
  {
    id: "perch",
    slug: "perch",
    name: "Окунь",
    description: "Короткие резкие рывки. Берёт на червя и мелкий силикон.",
    minWeightG: 70,
    avgWeightG: 320,
    maxWeightG: 2400,
    minLengthCm: 12,
    maxLengthCm: 45,
    rarity: "COMMON",
    trophyWeightG: 900,
    recordWeightG: 1500,
    baseXp: 16,
    baseValue: 9,
    fightProfile: { pull: 0.55, directionChange: 0.7, coverSeek: 0.25, stamina: 0.55 },
    activity: {
      seasons: ["SPRING", "SUMMER", "AUTUMN", "WINTER"],
      times: ["DAWN", "MORNING", "DAY", "EVENING"],
      weather: ["CLEAR", "PARTLY_CLOUDY", "OVERCAST", "WIND", "CALM"],
      depthMinM: 0.8,
      depthMaxM: 4.5,
      tempMinC: 4,
      tempMaxC: 22,
    },
    baits: ["worm", "maggot", "livebait"],
    lures: ["twister", "spinner"],
    behavior: "jerky",
    spots: [
      { spotId: "old-bridge", weight: 0.9 },
      { spotId: "reed-bank", weight: 1.1 },
      { spotId: "deep-hole", weight: 1.3 },
      { spotId: "snag", weight: 1 },
    ],
  },
  {
    id: "bream",
    slug: "bream",
    name: "Лещ",
    description: "Держится ямы. Любит мотыля и прикормку.",
    minWeightG: 200,
    avgWeightG: 900,
    maxWeightG: 4500,
    minLengthCm: 20,
    maxLengthCm: 55,
    rarity: "UNCOMMON",
    trophyWeightG: 2200,
    recordWeightG: 3400,
    baseXp: 24,
    baseValue: 16,
    fightProfile: { pull: 0.5, directionChange: 0.25, coverSeek: 0.1, stamina: 0.85 },
    activity: {
      seasons: ["SPRING", "SUMMER", "AUTUMN"],
      times: ["DAWN", "NIGHT", "EVENING", "DUSK"],
      weather: ["OVERCAST", "CALM", "PARTLY_CLOUDY", "FOG"],
      depthMinM: 2.2,
      depthMaxM: 5.5,
      tempMinC: 10,
      tempMaxC: 22,
    },
    baits: ["bloodworm", "worm", "corn", "dough"],
    lures: [],
    behavior: "heavy",
    spots: [{ spotId: "deep-hole", weight: 1.8 }, { spotId: "old-bridge", weight: 0.4 }],
  },
  {
    id: "tench",
    slug: "tench",
    name: "Линь",
    description: "Ил и камыш. Берёт нехотя, держит глухо.",
    minWeightG: 250,
    avgWeightG: 800,
    maxWeightG: 3500,
    minLengthCm: 18,
    maxLengthCm: 50,
    rarity: "UNCOMMON",
    trophyWeightG: 1800,
    recordWeightG: 2800,
    baseXp: 22,
    baseValue: 14,
    fightProfile: { pull: 0.6, directionChange: 0.2, coverSeek: 0.45, stamina: 0.9 },
    activity: {
      seasons: ["SUMMER", "AUTUMN"],
      times: ["DAWN", "DUSK", "NIGHT"],
      weather: ["CALM", "FOG", "OVERCAST", "CLEAR"],
      depthMinM: 0.6,
      depthMaxM: 2.4,
      tempMinC: 14,
      tempMaxC: 26,
    },
    baits: ["worm", "bloodworm", "dough"],
    lures: [],
    behavior: "dogged",
    spots: [{ spotId: "reed-bank", weight: 1.3 }, { spotId: "snag", weight: 0.6 }],
  },
  {
    id: "pike",
    slug: "pike",
    name: "Щука",
    description: "Сильные рывки, смена направления, уход в укрытие.",
    minWeightG: 400,
    avgWeightG: 1600,
    maxWeightG: 12000,
    minLengthCm: 35,
    maxLengthCm: 110,
    rarity: "RARE",
    trophyWeightG: 4500,
    recordWeightG: 8000,
    baseXp: 40,
    baseValue: 28,
    fightProfile: { pull: 0.95, directionChange: 0.9, coverSeek: 0.8, stamina: 1.1 },
    activity: {
      seasons: ["SPRING", "SUMMER", "AUTUMN", "WINTER"],
      times: ["DAWN", "MORNING", "EVENING", "DUSK"],
      weather: ["CLEAR", "PARTLY_CLOUDY", "OVERCAST", "WIND", "FOG"],
      depthMinM: 1,
      depthMaxM: 4.5,
      tempMinC: 2,
      tempMaxC: 20,
    },
    baits: ["livebait"],
    lures: ["spoon", "twister", "wobbler"],
    behavior: "predator",
    spots: [
      { spotId: "snag", weight: 1.7 },
      { spotId: "reed-bank", weight: 1.1 },
      { spotId: "deep-hole", weight: 0.7 },
    ],
  },
  {
    id: "ruffe",
    slug: "ruffe",
    name: "Ёрш",
    description: "Колючий донный житель. Часто мешает, но кормит новичка.",
    minWeightG: 20,
    avgWeightG: 60,
    maxWeightG: 180,
    minLengthCm: 8,
    maxLengthCm: 18,
    rarity: "COMMON",
    trophyWeightG: 120,
    recordWeightG: 160,
    baseXp: 6,
    baseValue: 2,
    fightProfile: { pull: 0.2, directionChange: 0.3, coverSeek: 0.05, stamina: 0.3 },
    activity: {
      seasons: ["SPRING", "SUMMER", "AUTUMN", "WINTER"],
      times: ["DAY", "MORNING", "EVENING", "NIGHT"],
      weather: ["CLEAR", "OVERCAST", "RAIN", "SNOW", "CALM"],
      depthMinM: 1,
      depthMaxM: 5,
      tempMinC: 0,
      tempMaxC: 20,
    },
    baits: ["worm", "maggot", "bloodworm"],
    lures: [],
    behavior: "nuisance",
    spots: [{ spotId: "deep-hole", weight: 1.4 }, { spotId: "old-bridge", weight: 0.7 }],
  },
  {
    id: "rudd",
    slug: "rudd",
    name: "Краснопёрка",
    description: "Верхний слой у камыша, вспышка золота на солнце.",
    minWeightG: 50,
    avgWeightG: 180,
    maxWeightG: 900,
    minLengthCm: 11,
    maxLengthCm: 34,
    rarity: "COMMON",
    trophyWeightG: 450,
    recordWeightG: 700,
    baseXp: 12,
    baseValue: 6,
    fightProfile: { pull: 0.35, directionChange: 0.45, coverSeek: 0.2, stamina: 0.45 },
    activity: {
      seasons: ["SPRING", "SUMMER"],
      times: ["MORNING", "DAY", "EVENING"],
      weather: ["CLEAR", "CALM", "PARTLY_CLOUDY"],
      depthMinM: 0.3,
      depthMaxM: 1.6,
      tempMinC: 14,
      tempMaxC: 28,
    },
    baits: ["bread", "maggot", "worm"],
    lures: ["spinner"],
    behavior: "surface",
    spots: [{ spotId: "reed-bank", weight: 1.6 }, { spotId: "sandy-spit", weight: 0.9 }],
  },
  {
    id: "carp",
    slug: "carp",
    name: "Карп",
    description: "Долгое сильное сопротивление. Бойлы, кукуруза, терпение.",
    minWeightG: 600,
    avgWeightG: 2800,
    maxWeightG: 18000,
    minLengthCm: 30,
    maxLengthCm: 95,
    rarity: "RARE",
    trophyWeightG: 8000,
    recordWeightG: 13000,
    baseXp: 48,
    baseValue: 36,
    fightProfile: { pull: 0.85, directionChange: 0.4, coverSeek: 0.35, stamina: 1.4 },
    activity: {
      seasons: ["SPRING", "SUMMER", "AUTUMN"],
      times: ["NIGHT", "DAWN", "DUSK", "EVENING"],
      weather: ["CALM", "OVERCAST", "PARTLY_CLOUDY", "FOG"],
      depthMinM: 1.5,
      depthMaxM: 4.5,
      tempMinC: 14,
      tempMaxC: 26,
    },
    baits: ["corn", "boilies", "dough", "worm"],
    lures: [],
    behavior: "long-fight",
    spots: [{ spotId: "deep-hole", weight: 1.2 }, { spotId: "old-bridge", weight: 0.5 }, { spotId: "sandy-spit", weight: 0.7 }],
  },
  {
    id: "zander",
    slug: "zander",
    name: "Судак",
    description: "Ночной хищник ямы. Джиг и живец.",
    minWeightG: 350,
    avgWeightG: 1400,
    maxWeightG: 9000,
    minLengthCm: 32,
    maxLengthCm: 90,
    rarity: "RARE",
    trophyWeightG: 4000,
    recordWeightG: 6500,
    baseXp: 38,
    baseValue: 30,
    fightProfile: { pull: 0.7, directionChange: 0.5, coverSeek: 0.3, stamina: 1 },
    activity: {
      seasons: ["SPRING", "AUTUMN", "SUMMER"],
      times: ["DUSK", "NIGHT", "DAWN"],
      weather: ["OVERCAST", "CALM", "FOG", "PARTLY_CLOUDY"],
      depthMinM: 2.5,
      depthMaxM: 5.5,
      tempMinC: 8,
      tempMaxC: 18,
    },
    baits: ["livebait"],
    lures: ["twister", "jig"],
    behavior: "night-predator",
    spots: [{ spotId: "deep-hole", weight: 1.5 }, { spotId: "snag", weight: 0.5 }],
  },
  {
    id: "ide",
    slug: "ide",
    name: "Язь",
    description: "Сильный универсум озера. Берёт и на поплавок, и на блесну.",
    minWeightG: 200,
    avgWeightG: 700,
    maxWeightG: 3200,
    minLengthCm: 18,
    maxLengthCm: 52,
    rarity: "UNCOMMON",
    trophyWeightG: 1600,
    recordWeightG: 2500,
    baseXp: 26,
    baseValue: 18,
    fightProfile: { pull: 0.65, directionChange: 0.55, coverSeek: 0.25, stamina: 0.8 },
    activity: {
      seasons: ["SPRING", "SUMMER", "AUTUMN"],
      times: ["DAWN", "MORNING", "EVENING"],
      weather: ["CLEAR", "PARTLY_CLOUDY", "RAIN", "WIND"],
      depthMinM: 0.8,
      depthMaxM: 3,
      tempMinC: 8,
      tempMaxC: 22,
    },
    baits: ["worm", "maggot", "bread"],
    lures: ["spinner", "spoon"],
    behavior: "versatile",
    spots: [
      { spotId: "old-bridge", weight: 0.8 },
      { spotId: "sandy-spit", weight: 1.2 },
      { spotId: "snag", weight: 0.6 },
    ],
  },
  {
    id: "pool-master",
    slug: "pool-master",
    name: "Хозяин Омута",
    description: "Легендарный сом ямы. Выходит в грозу и на падение давления.",
    minWeightG: 9000,
    avgWeightG: 14000,
    maxWeightG: 28000,
    minLengthCm: 120,
    maxLengthCm: 210,
    rarity: "LEGENDARY",
    trophyWeightG: 14000,
    recordWeightG: 18000,
    baseXp: 180,
    baseValue: 0,
    fightProfile: { pull: 1.3, directionChange: 0.35, coverSeek: 0.9, stamina: 2.2 },
    activity: {
      seasons: ["SUMMER", "AUTUMN"],
      times: ["NIGHT", "DUSK"],
      weather: ["STORM", "DOWNPOUR", "OVERCAST"],
      depthMinM: 4,
      depthMaxM: 5.5,
      tempMinC: 16,
      tempMaxC: 24,
    },
    baits: ["livebait"],
    lures: ["jig"],
    behavior: "legendary-bottom",
    legendary: true,
    legendaryLore: "Старожилы говорят, что он ломает снасти ещё до подсечки.",
    spots: [{ spotId: "deep-hole", weight: 0.08 }],
  },
];

export const items = [
  { id: "rod-willow", slug: "rod-willow", name: "Ивовый хлыст", description: "Стартовое поплавочное удилище.", kind: "ROD" as const, rarity: "COMMON" as const, stackable: false, maxStack: 1, value: 40, stats: { method: "FLOAT", length: 4, test: 12, power: 0.35, durability: 80 } },
  { id: "rod-spin-light", slug: "rod-spin-light", name: "Лёгкий спиннинг", description: "Для окуня и щуки у камыша.", kind: "ROD" as const, rarity: "COMMON" as const, stackable: false, maxStack: 1, value: 90, stats: { method: "SPINNING", length: 2.1, test: 18, power: 0.55, durability: 90 } },
  { id: "rod-feeder", slug: "rod-feeder", name: "Фидер «Бровка»", description: "Для ямы и леща.", kind: "ROD" as const, rarity: "UNCOMMON" as const, stackable: false, maxStack: 1, value: 160, stats: { method: "FEEDER", length: 3.6, test: 60, power: 0.7, durability: 100 } },
  { id: "reel-basic", slug: "reel-basic", name: "Катушка новичка", description: "Простой фрикцион.", kind: "REEL" as const, rarity: "COMMON" as const, stackable: false, maxStack: 1, value: 50, stats: { size: 2000, drag: 0.45, ratio: 5.2, durability: 80 } },
  { id: "reel-spin", slug: "reel-spin", name: "Спиннинговая 2500", description: "Быстрая подмотка.", kind: "REEL" as const, rarity: "UNCOMMON" as const, stackable: false, maxStack: 1, value: 140, stats: { size: 2500, drag: 0.7, ratio: 5.8, durability: 100 } },
  { id: "line-025", slug: "line-025", name: "Леска 0.25", description: "Разрыв около 4 кг.", kind: "LINE" as const, rarity: "COMMON" as const, stackable: true, maxStack: 5, value: 20, stats: { diameter: 0.25, strength: 0.7, stretch: 0.4, visibility: 0.5 } },
  { id: "line-braid", slug: "line-braid", name: "Шнур 0.10", description: "Чувствительный, мало растяжения.", kind: "LINE" as const, rarity: "UNCOMMON" as const, stackable: true, maxStack: 5, value: 70, stats: { diameter: 0.1, strength: 1.05, stretch: 0.1, visibility: 0.3 } },
  { id: "hook-10", slug: "hook-10", name: "Крючки №10", description: "Для плотвы и карася.", kind: "HOOK" as const, rarity: "COMMON" as const, stackable: true, maxStack: 50, value: 8, stats: { size: 10, quality: 0.55 } },
  { id: "hook-6", slug: "hook-6", name: "Крючки №6", description: "Универсал.", kind: "HOOK" as const, rarity: "COMMON" as const, stackable: true, maxStack: 40, value: 12, stats: { size: 6, quality: 0.7 } },
  { id: "float-goose", slug: "float-goose", name: "Гусиный поплавок", description: "Видно на ряби.", kind: "FLOAT" as const, rarity: "COMMON" as const, stackable: true, maxStack: 10, value: 10, stats: { visibility: 0.8 } },
  { id: "worm", slug: "worm", name: "Червь", description: "Классика. Можно накопать лопатой.", kind: "BAIT" as const, rarity: "COMMON" as const, stackable: true, maxStack: 40, value: 2, stats: { slug: "worm", dietKey: "worm", quality: "normal", spoilHours: 18 } },
  { id: "crawler", slug: "crawler", name: "Выползок", description: "Крупный червь. Ночью после дождя на влажной траве.", kind: "BAIT" as const, rarity: "UNCOMMON" as const, stackable: true, maxStack: 20, value: 8, stats: { slug: "crawler", dietKey: "crawler", quality: "fresh", spoilHours: 14 } },
  { id: "maggot", slug: "maggot", name: "Опарыш", description: "Для плотвы.", kind: "BAIT" as const, rarity: "COMMON" as const, stackable: true, maxStack: 60, value: 3, stats: { slug: "maggot", dietKey: "maggot", quality: "normal", spoilHours: 24 } },
  { id: "bloodworm", slug: "bloodworm", name: "Мотыль", description: "Ил у камыша, сито. Не лопата.", kind: "BAIT" as const, rarity: "UNCOMMON" as const, stackable: true, maxStack: 40, value: 6, stats: { slug: "bloodworm", dietKey: "bloodworm", quality: "fresh", spoilHours: 10 } },
  { id: "bread", slug: "bread", name: "Хлеб", description: "Карась и краснопёрка.", kind: "BAIT" as const, rarity: "COMMON" as const, stackable: true, maxStack: 20, value: 1, stats: { slug: "bread", dietKey: "bread", quality: "normal", spoilHours: 12 } },
  { id: "corn", slug: "corn", name: "Кукуруза", description: "Карп и карась.", kind: "BAIT" as const, rarity: "COMMON" as const, stackable: true, maxStack: 30, value: 4, stats: { slug: "corn", dietKey: "corn", quality: "normal", spoilHours: 36 } },
  { id: "dough", slug: "dough", name: "Тесто", description: "Самодельная насадка.", kind: "BAIT" as const, rarity: "COMMON" as const, stackable: true, maxStack: 20, value: 3, stats: { slug: "dough", dietKey: "dough", quality: "normal", spoilHours: 8 } },
  { id: "livebait", slug: "livebait", name: "Живец", description: "Для щуки и судака.", kind: "BAIT" as const, rarity: "UNCOMMON" as const, stackable: true, maxStack: 8, value: 12, stats: { slug: "livebait", dietKey: "livebait", quality: "fresh", spoilHours: 6 } },
  { id: "chafer-larva", slug: "chafer-larva", name: "Личинка майского жука", description: "Корни у сосен. Нужен навык добычи.", kind: "BAIT" as const, rarity: "RARE" as const, stackable: true, maxStack: 12, value: 18, stats: { slug: "chafer-larva", dietKey: "chafer-larva", quality: "fresh", spoilHours: 16 } },
  { id: "may-beetle", slug: "may-beetle", name: "Майский жук", description: "Сезон лёта. Вечер и ночь у деревьев.", kind: "BAIT" as const, rarity: "RARE" as const, stackable: true, maxStack: 10, value: 22, stats: { slug: "may-beetle", dietKey: "may-beetle", quality: "fresh", spoilHours: 8 } },
  { id: "mole-cricket", slug: "mole-cricket", name: "Медведка", description: "Пойменный луг, рыхлая влажная земля.", kind: "BAIT" as const, rarity: "EPIC" as const, stackable: true, maxStack: 6, value: 40, stats: { slug: "mole-cricket", dietKey: "mole-cricket", quality: "fresh", spoilHours: 10 } },
  { id: "boilies", slug: "boilies", name: "Бойлы сладкие 14 мм", description: "Тонущая карповая насадка.", kind: "BAIT" as const, rarity: "UNCOMMON" as const, stackable: true, maxStack: 40, value: 15, stats: { slug: "boilies", dietKey: "boilies", sizeMm: 14, aroma: "sweet", buoyancy: "sinking", spoilHours: 90 } },
  { id: "boilie-fish-18", slug: "boilie-fish-18", name: "Бойлы рыба 18 мм", description: "Холодная вода, рыбная мука.", kind: "BAIT" as const, rarity: "UNCOMMON" as const, stackable: true, maxStack: 30, value: 22, stats: { slug: "boilies", dietKey: "boilies", sizeMm: 18, aroma: "fish", buoyancy: "sinking", spoilHours: 90 } },
  { id: "boilie-popup-12", slug: "boilie-popup-12", name: "Pop-up 12 мм", description: "Всплывающий. Снежок с тонущим бойлом.", kind: "BAIT" as const, rarity: "UNCOMMON" as const, stackable: true, maxStack: 24, value: 24, stats: { slug: "boilies", dietKey: "boilies", sizeMm: 12, aroma: "fruit", buoyancy: "popup", spoilHours: 90 } },
  { id: "boilie-wafter-16", slug: "boilie-wafter-16", name: "Wafters 16 мм", description: "Нейтральная плавучесть.", kind: "BAIT" as const, rarity: "UNCOMMON" as const, stackable: true, maxStack: 24, value: 26, stats: { slug: "boilies", dietKey: "boilies", sizeMm: 16, aroma: "spicy", buoyancy: "wafter", spoilHours: 90 } },
  { id: "spoon", slug: "spoon", name: "Колеблющаяся блесна", description: "Щука у коряг.", kind: "LURE" as const, rarity: "COMMON" as const, stackable: true, maxStack: 8, value: 25, stats: { slug: "spoon", dietKey: "spoon", sizeMm: 80 } },
  { id: "spinner", slug: "spinner", name: "Вертушка", description: "Окунь и язь.", kind: "LURE" as const, rarity: "COMMON" as const, stackable: true, maxStack: 8, value: 22, stats: { slug: "spinner", dietKey: "spinner", sizeMm: 45 } },
  { id: "twister", slug: "twister", name: "Твистер", description: "Силикон на джиг.", kind: "LURE" as const, rarity: "COMMON" as const, stackable: true, maxStack: 15, value: 8, stats: { slug: "twister", dietKey: "twister", sizeMm: 70 } },
  { id: "wobbler", slug: "wobbler", name: "Воблер минноу", description: "Проводка у камыша.", kind: "LURE" as const, rarity: "UNCOMMON" as const, stackable: true, maxStack: 6, value: 55, stats: { slug: "wobbler", dietKey: "wobbler", sizeMm: 90 } },
  { id: "jig", slug: "jig", name: "Джиг-головка", description: "Яма и судак.", kind: "LURE" as const, rarity: "COMMON" as const, stackable: true, maxStack: 12, value: 10, stats: { slug: "jig", dietKey: "jig", sizeMm: 80 } },
  { id: "shovel", slug: "shovel", name: "Малая лопата", description: "Копать червей после дождя.", kind: "TOOL" as const, rarity: "COMMON" as const, stackable: false, maxStack: 1, value: 30, stats: { harvest: "worm" } },
  { id: "sieve", slug: "sieve", name: "Сито", description: "Мотыль из ила, не из сухой земли.", kind: "TOOL" as const, rarity: "COMMON" as const, stackable: false, maxStack: 1, value: 18, stats: { harvest: "bloodworm" } },
  { id: "bait-box", slug: "bait-box", name: "Контейнер для наживки", description: "Замедляет порчу живой насадки.", kind: "TOOL" as const, rarity: "COMMON" as const, stackable: false, maxStack: 1, value: 28, stats: { storage: "cool", spoilMul: 0.55 } },
  { id: "groundbait", slug: "groundbait", name: "Прикормка «Озеро»", description: "Базовая смесь. Не мгновенный клёв.", kind: "CONSUMABLE" as const, rarity: "COMMON" as const, stackable: true, maxStack: 10, value: 14, stats: { mix: true, targetSpecies: ["crucian", "roach", "bream", "rudd", "tench", "ide"], nutritionalValue: 0.55, attraction: 0.7, particle: 0.5 } },
  { id: "groundbait-bream", slug: "groundbait-bream", name: "Прикормка «Лещ»", description: "Мелкая фракция, для ямы.", kind: "CONSUMABLE" as const, rarity: "UNCOMMON" as const, stackable: true, maxStack: 8, value: 22, stats: { mix: true, targetSpecies: ["bream", "roach", "ruffe", "ide"], nutritionalValue: 0.72, attraction: 0.88, particle: 0.35 } },
  { id: "groundbait-carp", slug: "groundbait-carp", name: "Прикормка «Карп»", description: "Питательная. Легко перекормить.", kind: "CONSUMABLE" as const, rarity: "UNCOMMON" as const, stackable: true, maxStack: 8, value: 26, stats: { mix: true, targetSpecies: ["carp", "crucian", "tench"], nutritionalValue: 0.92, attraction: 0.8, particle: 0.42 } },
  { id: "tent-1", slug: "tent-1", name: "Палатка «Роса»", description: "Укрытие от дождя.", kind: "TENT" as const, rarity: "COMMON" as const, stackable: false, maxStack: 1, value: 120, stats: { rain: 0.6, cold: 0.3, rest: 0.4 } },
  { id: "bread-food", slug: "bread-food", name: "Бутерброд", description: "Снимает голод.", kind: "FOOD" as const, rarity: "COMMON" as const, stackable: true, maxStack: 8, value: 6, stats: { hunger: -25, stamina: 8 } },
  { id: "tea", slug: "tea", name: "Чай в термосе", description: "Тепло и жажда.", kind: "DRINK" as const, rarity: "COMMON" as const, stackable: true, maxStack: 6, value: 5, stats: { thirst: -20, warmth: 10 } },
  { id: "water", slug: "water", name: "Фляга воды", description: "Питьё.", kind: "DRINK" as const, rarity: "COMMON" as const, stackable: true, maxStack: 6, value: 3, stats: { thirst: -30 } },
  { id: "leader", slug: "leader", name: "Поводок", description: "Крафт оснастки.", kind: "LEADER" as const, rarity: "COMMON" as const, stackable: true, maxStack: 20, value: 6, stats: {} },
  { id: "hat-cap", slug: "hat-cap", name: "Кепка", description: "Косметика, без бонуса клёва.", kind: "COSMETIC" as const, rarity: "COMMON" as const, stackable: false, maxStack: 1, value: 20, stats: { slot: "hat" }, cosmetic: true },
];

export const shops = [
  { id: "forest-tackle", slug: "forest-tackle", name: "Лавка у озера", kind: "TACKLE" as const, region: "forest", items: ["rod-willow", "rod-spin-light", "rod-feeder", "reel-basic", "reel-spin", "line-025", "line-braid", "hook-10", "hook-6", "float-goose", "leader"] },
  { id: "forest-bait", slug: "forest-bait", name: "Наживки и смеси", kind: "BAIT" as const, region: "forest", items: ["worm", "maggot", "bloodworm", "bread", "corn", "dough", "livebait", "boilies", "boilie-fish-18", "boilie-popup-12", "boilie-wafter-16", "groundbait", "groundbait-bream", "groundbait-carp"] },
  { id: "forest-lure", slug: "forest-lure", name: "Приманки", kind: "LURE" as const, region: "forest", items: ["spoon", "spinner", "twister", "wobbler", "jig"] },
  { id: "forest-camp", slug: "forest-camp", name: "Туристический угол", kind: "CAMP" as const, region: "forest", items: ["tent-1", "shovel", "sieve", "bait-box", "bread-food", "tea", "water", "hat-cap"] },
];

export const recipes = [
  { id: "rig-float", slug: "rig-float", name: "Поплавочная оснастка", kind: "rig", station: "tackle", ingredients: [{ itemId: "leader", qty: 1 }, { itemId: "hook-10", qty: 1 }, { itemId: "float-goose", qty: 1 }], outputs: [{ itemId: "leader", qty: 1 }] },
  { id: "dough-mix", slug: "dough-mix", name: "Тесто", kind: "bait", station: "camp", ingredients: [{ itemId: "bread", qty: 2 }], outputs: [{ itemId: "dough", qty: 3 }] },
  { id: "ukha", slug: "ukha", name: "Уха", kind: "food", station: "campfire", ingredients: [{ itemId: "bread-food", qty: 1 }, { itemId: "water", qty: 1 }], outputs: [{ itemId: "bread-food", qty: 1 }] },
];

export const fauna = [
  { id: "duck", slug: "duck", name: "Кряква", kind: "bird", description: "Сидение на воде, взлёт от заброса.", rare: false, dangerous: false, hint: "Стая у камыша иногда выдаёт малька." },
  { id: "heron", slug: "heron", name: "Цапля", kind: "bird", description: "Стоит в заводи.", rare: false, dangerous: false, hint: "Цапля выбирает мелкие охотничьи окна." },
  { id: "gull", slug: "gull", name: "Чайка", kind: "bird", description: "Кружит над открытой водой.", rare: false, dangerous: false, hint: null },
  { id: "squirrel", slug: "squirrel", name: "Белка", kind: "small", description: "Шумит в соснах.", rare: false, dangerous: false, hint: null },
  { id: "beaver", slug: "beaver", name: "Бобр", kind: "small", description: "Чуть меняет струю у коряг.", rare: false, dangerous: false, hint: "Свежие погрызы — рядом тихое течение." },
  { id: "moose", slug: "moose", name: "Лось", kind: "large", description: "На дальнем берегу на рассвете.", rare: true, dangerous: false, hint: null },
  { id: "bear", slug: "bear", name: "Медведь", kind: "large", description: "Редок. Интересуется брошенной едой. Не боевая система.", rare: true, dangerous: true, hint: "Уберите еду и отойдите." },
];

export const npcs = [
  { id: "mikhalych", slug: "mikhalych", name: "Михалыч", role: "keeper", waterbodyId: "forest-lake", greeting: "На яме сегодня тихо, а у мостика карась шевелится.", rumors: ["После дождя червя копай у тропы.", "Хозяин Омута любит грозу."] },
  { id: "lara", slug: "lara", name: "Лара", role: "vendor", waterbodyId: "forest-lake", greeting: "Вертушки почти разобрали, блесны ещё есть.", rumors: ["На косе краснопёрка, если найдёшь подход."] },
];

export const quests = [
  {
    id: "first-fish",
    slug: "first-fish",
    npcId: "mikhalych",
    kind: "STORY" as const,
    title: "Первая рыба",
    description: "Поймайте любую рыбу на Лесном озере.",
    objectives: [{ type: "catch_any", count: 1 }],
    rewards: { xp: 40, coins: 30, items: [{ itemId: "maggot", qty: 10 }] },
  },
  {
    id: "bridge-crucian",
    slug: "bridge-crucian",
    npcId: "mikhalych",
    kind: "DAILY" as const,
    title: "Карась у мостика",
    description: "Поймайте карася на Старом мостике.",
    objectives: [{ type: "catch_species", speciesId: "crucian", spotId: "old-bridge", count: 1 }],
    rewards: { xp: 25, coins: 20 },
  },
];
