/**
 * APPROVED WAIT — LOCKED
 *
 * Accepted at HEAD 2b3a5c3848f061caa9e8f7c2b72918f1ba1952e6
 *   feat(frontend): add WAIT loop after float landing
 *
 * Do not edit this file to "improve" WAIT.
 * BITE / HOOKSET / REEL / FIGHT / LAND must start FROM this wait,
 * not by rewriting it.
 *
 * Chain:
 *   IDLE
 *     → READY              (approvedReady.ts)
 *       → PRE-CAST         (approvedPrecast.ts)
 *         → CAST           (approvedCast.ts)
 *           → FLOAT LANDING (approvedFloatLanding.ts)
 *             → WAIT        (this file)
 *               → BITE      (not implemented)
 *
 * Locked:
 *   first WAIT frame matches last FLOAT LANDING
 *   rod stays parented to Hand_R
 *   reel under the blank; grip unchanged
 *   tip lower than PRE-CAST, blank toward the water
 *   line RodTip → FloatAttach with light sag
 *   float stays vertical on approved FloatWaterline
 *   antenna above water, keel below
 *   light bob only — no bite
 *   almost-static loop, light breathing
 *   IDLE / READY / PRE-CAST / CAST / FLOAT LANDING unchanged
 *
 * Debug button "Wait" in /dev/rig3d may remain.
 */
import { APPROVED_READY_COMMIT } from "./approvedReady";
import { APPROVED_PRECAST_COMMIT } from "./approvedPrecast";
import { APPROVED_TACKLE_COMMIT } from "./approvedTackle";
import { APPROVED_CAST_COMMIT } from "./approvedCast";
import { APPROVED_FLOAT_LANDING_COMMIT } from "./approvedFloatLanding";

export const APPROVED_WAIT_COMMIT =
  "2b3a5c3848f061caa9e8f7c2b72918f1ba1952e6";

export const APPROVED_WAIT_CHAIN = {
  ready: APPROVED_READY_COMMIT,
  tackle: APPROVED_TACKLE_COMMIT,
  precast: APPROVED_PRECAST_COMMIT,
  cast: APPROVED_CAST_COMMIT,
  floatLanding: APPROVED_FLOAT_LANDING_COMMIT,
  wait: APPROVED_WAIT_COMMIT,
} as const;
