/**
 * APPROVED PRE-CAST → CAST TRANSITION — LOCKED
 *
 * Accepted at HEAD 22e0f82748bb12597228c56c8af53a13359ea969
 *   fix(frontend): stop PRE-CAST to CAST arm snap
 *
 * Do not edit this file to "improve" the transition.
 * Do not revert the snap fix.
 * WAIT / BITE / HOOKSET / REEL / FIGHT / LAND / FLOAT LANDING
 * must start FROM this CAST, not by rewriting it.
 *
 * Chain:
 *   IDLE
 *     → READY          (approvedReady.ts)
 *       → PRE-CAST     (approvedPrecast.ts)
 *         → CAST       (this file)
 *
 * Locked transition:
 *   first CAST frame matches last PRE-CAST
 *   rod stays parented to Hand_R (gripKey "hold")
 *   AIM arm overlays stay on; CAST offsets add on top via applyArmSpins
 *   blank pitch is captured from the live PRE-CAST rod, then delta-applied
 *   do not reseat onto AIM_PITCH 42° / AIM_YAW 4°
 *   do not reparent Hand_R → character root
 *   do not drop AIM offsets for one frame
 *   reel stays under the blank; fist / RodGrip unchanged
 *
 * CAST character (also locked):
 *   short float-rod backswing, forward, release, follow-through
 */
import { APPROVED_READY_COMMIT } from "./approvedReady";
import { APPROVED_PRECAST_COMMIT } from "./approvedPrecast";
import { APPROVED_TACKLE_COMMIT } from "./approvedTackle";

export const APPROVED_CAST_COMMIT =
  "22e0f82748bb12597228c56c8af53a13359ea969";

export const APPROVED_CAST_TRANSITION = {
  ready: APPROVED_READY_COMMIT,
  tackle: APPROVED_TACKLE_COMMIT,
  precast: APPROVED_PRECAST_COMMIT,
  cast: APPROVED_CAST_COMMIT,
} as const;
