/**
 * APPROVED LAND PREP — LOCKED
 *
 * Accepted at HEAD abf5d891dc2ed70c9c237d27203b0a4fc97654eb
 *   fix(frontend): keep LAND PREP FishPullPoint at the waterline
 *
 * Do not edit this file to "improve" LAND PREP.
 * LAND / production fish / catch result must start FROM this state,
 * not by rewriting it.
 *
 * Chain:
 *   IDLE
 *     → READY              (approvedReady.ts)
 *       → PRE-CAST         (approvedPrecast.ts)
 *         → CAST           (approvedCast.ts)
 *           → FLOAT LANDING (approvedFloatLanding.ts)
 *             → WAIT        (approvedWait.ts)
 *               → BITE      (approvedHookset.ts)
 *                 → HOOKSET (approvedHookset.ts)
 *                   → FIGHT_LIGHT (approvedFight.ts)
 *                     → REEL
 *                       → LAND PREP (this file)
 *                         → LAND (not implemented)
 *
 * Locked tackle topology (do not shortcut):
 *   RodTip → FloatAttach → FLOAT → FloatBottom → leader → FishPullPoint
 *   upper line: RodTip → FloatAttach
 *   leader:     FloatBottom → FishPullPoint
 *   never RodTip → FishPullPoint bypassing the float
 *
 * Locked finals:
 *   float Y = 0.72 (in air)
 *   waterline Y = 0
 *   FishPullPoint Y = -0.12 (still in water)
 *   horizontal distance ≈ 1.08 m
 *   first LAND PREP frame matches last REEL
 *   rod stays parented to Hand_R
 *   LAND does not start
 *   previous approved states unchanged
 *
 * Debug button "Approach" in /dev/rig3d may remain.
 */
import { APPROVED_READY_COMMIT } from "./approvedReady";
import { APPROVED_PRECAST_COMMIT } from "./approvedPrecast";
import { APPROVED_TACKLE_COMMIT } from "./approvedTackle";
import { APPROVED_CAST_COMMIT } from "./approvedCast";
import { APPROVED_FLOAT_LANDING_COMMIT } from "./approvedFloatLanding";
import { APPROVED_WAIT_COMMIT } from "./approvedWait";
import { APPROVED_BITE_COMMIT, APPROVED_HOOKSET_COMMIT } from "./approvedHookset";
import { APPROVED_FIGHT_COMMIT, APPROVED_FIGHT_TOPOLOGY } from "./approvedFight";

export const APPROVED_LAND_PREP_COMMIT =
  "abf5d891dc2ed70c9c237d27203b0a4fc97654eb";

export const APPROVED_LAND_PREP_TOPOLOGY = APPROVED_FIGHT_TOPOLOGY;

export const APPROVED_LAND_PREP_FINALS = {
  floatY: 0.72,
  waterlineY: 0,
  fishPullY: -0.12,
  distance: 1.08,
} as const;

export const APPROVED_LAND_PREP_CHAIN = {
  ready: APPROVED_READY_COMMIT,
  tackle: APPROVED_TACKLE_COMMIT,
  precast: APPROVED_PRECAST_COMMIT,
  cast: APPROVED_CAST_COMMIT,
  floatLanding: APPROVED_FLOAT_LANDING_COMMIT,
  wait: APPROVED_WAIT_COMMIT,
  bite: APPROVED_BITE_COMMIT,
  hookset: APPROVED_HOOKSET_COMMIT,
  fight: APPROVED_FIGHT_COMMIT,
  landPrep: APPROVED_LAND_PREP_COMMIT,
} as const;
