/**
 * APPROVED FLOAT LANDING — LOCKED
 *
 * Accepted at HEAD e3d39e9d2c59a55dd7249a1225a353ebbe48e2d7
 *   feat(frontend): add FLOAT LANDING after CAST
 *
 * Do not edit this file to "improve" FLOAT LANDING.
 * WAIT / BITE / HOOKSET / REEL / FIGHT / LAND must start FROM this
 * landing, not by rewriting it.
 *
 * Chain:
 *   IDLE
 *     → READY              (approvedReady.ts)
 *       → PRE-CAST         (approvedPrecast.ts)
 *         → CAST           (approvedCast.ts)
 *           → FLOAT LANDING (this file)
 *             → WAIT        (not implemented)
 *
 * Locked:
 *   starts from last CAST frame, no teleport
 *   live CAST pos/vel continue
 *   line RodTip → FloatAttach stays intact
 *   first contact is the keel (FloatBottom), not the body center
 *   small splash + 2 thin ripple rings, fast fade
 *   light dip, then upright settle on approved FloatWaterline
 *   antenna above water, keel below
 *   slight line sag after settle
 *   fisherman stays in CAST follow-through
 *   rod stays parented to Hand_R
 *   READY / PRE-CAST / CAST unchanged
 *
 * Internal phase CAST → FLOAT LANDING → (future WAIT).
 * Debug button "Landing" in /dev/rig3d may remain.
 */
import { APPROVED_READY_COMMIT } from "./approvedReady";
import { APPROVED_PRECAST_COMMIT } from "./approvedPrecast";
import { APPROVED_TACKLE_COMMIT } from "./approvedTackle";
import { APPROVED_CAST_COMMIT } from "./approvedCast";

export const APPROVED_FLOAT_LANDING_COMMIT =
  "e3d39e9d2c59a55dd7249a1225a353ebbe48e2d7";

export const APPROVED_FLOAT_LANDING_CHAIN = {
  ready: APPROVED_READY_COMMIT,
  tackle: APPROVED_TACKLE_COMMIT,
  precast: APPROVED_PRECAST_COMMIT,
  cast: APPROVED_CAST_COMMIT,
  floatLanding: APPROVED_FLOAT_LANDING_COMMIT,
} as const;
