/**
 * APPROVED READY + LINE + FLOAT CHAIN — LOCKED
 *
 * Accepted at HEAD c804d16dd2b4c4ec1b0d478fa441377145b6875c
 * Do not edit this file to "improve" the tackle.
 * Future clips must start FROM this chain, not by rewriting it.
 *
 * Fisherman READY
 *   → Hand_R / RodGrip
 *   → production rod.glb
 *   → RodTip / LineStart
 *   → fishing line (quadratic sag)
 *   → FloatAttach
 *   → production float.glb
 */
import * as THREE from "three";
import { APPROVED_READY_COMMIT, READY_FISHERMAN_PATH, READY_ROD_PATH } from "./approvedReady";

export const APPROVED_TACKLE_COMMIT =
  "c804d16dd2b4c4ec1b0d478fa441377145b6875c";

export const APPROVED_CHAIN = {
  ready: APPROVED_READY_COMMIT,
  tackle: APPROVED_TACKLE_COMMIT,
  fisherman: READY_FISHERMAN_PATH,
  rod: READY_ROD_PATH,
  float: "/models/production/float.glb",
  rodTip: "RodTip",
  lineStart: "LineStart",
  floatAttach: "FloatAttach",
  floatWaterline: "FloatWaterline",
  floatBottom: "FloatBottom",
} as const;

/** Line: RodTip → FloatAttach */
export const LINE_SEGMENTS = 22;
export const LINE_FLOATS = (LINE_SEGMENTS + 1) * 3;
export const LINE_SAG_LERP = 0.48;
export const LINE_SAG_BASE = 0.18;
export const LINE_SAG_SPAN = 0.12;
export const LINE_SAG_CAP = 0.55;
export const LINE_OPACITY_0 = 0.38;
export const LINE_OPACITY_SPAN = 0.18;
export const LINE_COLOR = 0xc9d0d5;
export const LINE_WIDTH_PX = 1.55;

/** Float: man-local, waterline at y=0, in front along −X */
export const FLOAT_X = -4.15;
export const WATER_Y = 0;
export const FLOAT_SCALE = 1.35;
export const FLOAT_BOB_AMP = 0.007;
export const FLOAT_BOB_FREQ = 1.25;
export const FLOAT_TILT_X = 0.04;
export const FLOAT_TILT_X_FREQ = 0.85;
export const FLOAT_TILT_Z = 0.032;
export const FLOAT_TILT_Z_FREQ = 1.05;
export const FLOAT_ATTACH_LOCAL = new THREE.Vector3(0, 0.114, 0);

export const WATER_POS = new THREE.Vector3(-4.6, -0.006, 0);
export const WATER_SIZE: [number, number] = [8.2, 6.4];
export const WATER_COLOR = "#2a4a52";
export const WATER_OPACITY = 0.58;

export const FLOAT_PATH = "/models/production/float.glb";
