/**
 * APPROVED HOOKSET — LOCKED
 *
 * Accepted at HEAD f9b312ee8dc0bfa5fd1bc779bb94f05119621903
 *   feat(frontend): add HOOKSET after BITE
 *
 * Do not edit this file to "improve" HOOKSET.
 * REEL / FIGHT / LAND must start FROM this strike, not by rewriting it.
 *
 * Chain:
 *   IDLE
 *     → READY              (approvedReady.ts)
 *       → PRE-CAST         (approvedPrecast.ts)
 *         → CAST           (approvedCast.ts)
 *           → FLOAT LANDING (approvedFloatLanding.ts)
 *             → WAIT        (approvedWait.ts)
 *               → BITE      (5f821107ce89f806eb9a037bd4085314d02635f8)
 *                 → HOOKSET (this file)
 *                   → FIGHT (not implemented)
 *
 * Locked:
 *   first HOOKSET frame matches last BITE
 *   rod stays parented to Hand_R
 *   reel under the blank; grip unchanged
 *   tip lifts to ~58°, not vertical
 *   line tightens quickly with light tip flex
 *   float pops slightly and pulls toward the angler
 *   hold shows resistance; FIGHT does not start
 *   IDLE / READY / PRE-CAST / CAST / FLOAT LANDING / WAIT / BITE unchanged
 *
 * Debug button "Hookset" in /dev/rig3d may remain.
 */
import { APPROVED_READY_COMMIT } from "./approvedReady";
import { APPROVED_PRECAST_COMMIT } from "./approvedPrecast";
import { APPROVED_TACKLE_COMMIT } from "./approvedTackle";
import { APPROVED_CAST_COMMIT } from "./approvedCast";
import { APPROVED_FLOAT_LANDING_COMMIT } from "./approvedFloatLanding";
import { APPROVED_WAIT_COMMIT } from "./approvedWait";

export const APPROVED_BITE_COMMIT =
  "5f821107ce89f806eb9a037bd4085314d02635f8";

export const APPROVED_HOOKSET_COMMIT =
  "f9b312ee8dc0bfa5fd1bc779bb94f05119621903";

export const APPROVED_HOOKSET_CHAIN = {
  ready: APPROVED_READY_COMMIT,
  tackle: APPROVED_TACKLE_COMMIT,
  precast: APPROVED_PRECAST_COMMIT,
  cast: APPROVED_CAST_COMMIT,
  floatLanding: APPROVED_FLOAT_LANDING_COMMIT,
  wait: APPROVED_WAIT_COMMIT,
  bite: APPROVED_BITE_COMMIT,
  hookset: APPROVED_HOOKSET_COMMIT,
} as const;
