/**
 * APPROVED READY BASELINE — LOCKED
 *
 * Accepted at HEAD 738c874a8cfc4744a6c43c22d72288f4dea6a44f
 * Do not edit this file to "improve" READY.
 * Future clips (AIM / CAST / WAIT / REEL / FIGHT) must start FROM these values,
 * not by rewriting READY.
 *
 * Locked:
 * - fisherman READY clip pose (IDLE-derived, fingers/wrist overlays below)
 * - rod local orientation: blank man-local (−cos 30°, sin 30°, 0), reel −Y
 * - rod in the closed right fist, 4 cm toward torso
 * - production rod.glb geometry (untouched)
 */
import * as THREE from "three";

export const APPROVED_READY_COMMIT =
  "738c874a8cfc4744a6c43c22d72288f4dea6a44f";

export const DEG = Math.PI / 180;

/** Blank pitch above man-local horizon. Reel under the blank. */
export const READY_PITCH = 30 * DEG;

/** Cork station along blank +Y from RodGrip. */
export const READY_REEL_SEAT_ALONG = 0.11;

/** Right Hand_R extra local-X from clip rest. */
export const READY_WRIST_OUT = 12 * DEG;

/** Right Hand_R extra local-Y: thumb away from torso. */
export const READY_THUMB_OUT = 33 * DEG;

/** Man-local +Z translation of the rod toward the torso. */
export const READY_NUDGE_IN = new THREE.Vector3(0, 0, 0.04);

/** Local-Z finger curl on the right hand, from clip rest. */
export const READY_FIST_Z: Readonly<Record<string, number>> = {
  Index_R_1: -42 * DEG,
  Index_R_2: -58 * DEG,
  Index_R_3: -32 * DEG,
  Middle_R_1: -40 * DEG,
  Middle_R_2: -60 * DEG,
  Middle_R_3: -34 * DEG,
  Ring_R_1: -38 * DEG,
  Ring_R_2: -56 * DEG,
  Ring_R_3: -32 * DEG,
  Pinky_R_1: -34 * DEG,
  Pinky_R_2: -52 * DEG,
  Pinky_R_3: -30 * DEG,
  Thumb_R_2: -24 * DEG,
  Thumb_R_3: -18 * DEG,
};

export const READY_ROD_PATH = "/models/production/rod.glb";
export const READY_FISHERMAN_PATH = "/models/production/fisherman.glb";
