/**
 * APPROVED FIGHT_LIGHT — LOCKED
 *
 * Accepted at HEAD 5d7e6ea3d712842444838f233345a2ad9cdb6885
 *   fix(frontend): keep fight line on float, add leader
 * Pose/loop from 499c8048d7206d7faf7f536d54cda6694a51a371
 *
 * Do not edit this file to "improve" FIGHT.
 * REEL / FIGHT_HEAVY / LAND / production fish must start FROM this fight,
 * not by rewriting it.
 *
 * Chain:
 *   IDLE
 *     → READY              (approvedReady.ts)
 *       → PRE-CAST         (approvedPrecast.ts)
 *         → CAST           (approvedCast.ts)
 *           → FLOAT LANDING (approvedFloatLanding.ts)
 *             → WAIT        (approvedWait.ts)
 *               → BITE      (approvedHookset.ts)
 *                 → HOOKSET (approvedHookset.ts)
 *                   → FIGHT_LIGHT (this file)
 *                     → LAND (not implemented)
 *
 * Locked tackle topology (do not shortcut):
 *   RodTip → FloatAttach → FLOAT → FloatBottom → leader → FishPullPoint
 *   upper line: RodTip → FloatAttach
 *   leader:     FloatBottom → FishPullPoint
 *   never RodTip → FishPullPoint bypassing the float
 *
 * Locked:
 *   first FIGHT frame matches last HOOKSET
 *   rod stays parented to Hand_R
 *   reel under the blank; grip unchanged
 *   compact hold with two light pulls in a 5s loop
 *   tip flex follows tension
 *   FloatAttach / FloatBottom travel with the float
 *   debug markers only via Line toggle
 *   LAND does not start
 *   previous approved states unchanged
 *
 * Debug button "Fight" in /dev/rig3d may remain.
 */
import { APPROVED_READY_COMMIT } from "./approvedReady";
import { APPROVED_PRECAST_COMMIT } from "./approvedPrecast";
import { APPROVED_TACKLE_COMMIT } from "./approvedTackle";
import { APPROVED_CAST_COMMIT } from "./approvedCast";
import { APPROVED_FLOAT_LANDING_COMMIT } from "./approvedFloatLanding";
import { APPROVED_WAIT_COMMIT } from "./approvedWait";
import { APPROVED_BITE_COMMIT, APPROVED_HOOKSET_COMMIT } from "./approvedHookset";

export const APPROVED_FIGHT_COMMIT =
  "5d7e6ea3d712842444838f233345a2ad9cdb6885";

export const APPROVED_FIGHT_TOPOLOGY = [
  "RodTip",
  "FloatAttach",
  "FLOAT",
  "FloatBottom",
  "leader",
  "FishPullPoint",
] as const;

export const APPROVED_FIGHT_CHAIN = {
  ready: APPROVED_READY_COMMIT,
  tackle: APPROVED_TACKLE_COMMIT,
  precast: APPROVED_PRECAST_COMMIT,
  cast: APPROVED_CAST_COMMIT,
  floatLanding: APPROVED_FLOAT_LANDING_COMMIT,
  wait: APPROVED_WAIT_COMMIT,
  bite: APPROVED_BITE_COMMIT,
  hookset: APPROVED_HOOKSET_COMMIT,
  fight: APPROVED_FIGHT_COMMIT,
} as const;
