/**
 * APPROVED PRE-CAST (AIM) BASELINE — LOCKED
 *
 * Accepted at HEAD f9097991039998213e518e957eb20b34db8ac83d
 * Do not edit this file to "improve" PRE-CAST.
 * BACKSWING / CAST must start FROM these values.
 *
 * Chain:
 *   READY (approvedReady.ts)
 *     → PRE-CAST
 *       rod 42°, reel under, READY grip
 *       float off water, hanging under RodTip
 *       slack line RodTip → FloatAttach
 */
import { DEG } from "./approvedReady";
import { APPROVED_READY_COMMIT } from "./approvedReady";
import { APPROVED_TACKLE_COMMIT } from "./approvedTackle";

export const APPROVED_PRECAST_COMMIT =
  "f9097991039998213e518e957eb20b34db8ac83d";

export const APPROVED_CAST_CHAIN = {
  ready: APPROVED_READY_COMMIT,
  tackle: APPROVED_TACKLE_COMMIT,
  precast: APPROVED_PRECAST_COMMIT,
} as const;

export const AIM_PITCH = 42 * DEG;
export const AIM_YAW = 4 * DEG;
export const AIM_LINE_TENSION = 0.05;
export const PRECAST_HANG_DROP = 1.08;
export const PRECAST_HANG_IN = 0.16;

export const PRECAST_SPINE_X = 5 * DEG;
export const PRECAST_SPINE1_X = 3 * DEG;
export const PRECAST_NECK_X = 5 * DEG;
export const PRECAST_HEAD_X = 4 * DEG;
